
widgets:
- recent_posts
- category
- tagcloud

excerpt_link: Read More ›

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: false
  twitter: true
  google: true
  pinterest: false

google_analytics:
